# Generated by Django 2.1.2 on 2018-11-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta',
            name='respuesta',
            field=models.CharField(default='lo que sea', max_length=100),
        ),
    ]
