# Generated by Django 2.1.3 on 2018-11-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_propuesta_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuesta',
            name='respuesta',
            field=models.TextField(default='lo que sea'),
        ),
    ]
