# Generated by Django 2.1.3 on 2018-11-20 07:04

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20181120_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuesta',
            name='respuesta',
            field=jsonfield.fields.JSONField(),
        ),
    ]
