# Generated by Django 2.1.3 on 2018-11-20 07:23

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_auto_20181120_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuesta',
            name='respuesta',
            field=jsonfield.fields.JSONCharField(default='lo que sea', max_length=1000),
        ),
    ]
